### ISSUE TITLE
Feature: Interpolate variables in inline configs/secrets

### ISSUE THREAD

**Issue by Radiergummi** [matchory/docker-swarm-deployment-action#5]
In a compose-spec file, we can use inline secrets that reference shell-style variables:

```yaml
configs:
  redis:
    content: |
      save ''
      appendonly no
      user ${REDIS_USERNAME:-app} on >${REDIS_PASSWORD:-app} ~* +@all -@admin
```

That makes for a pretty convincing case to assemble complex configuration *within* the compose file. Currently, that content would end up in the stack config as-is (ie., not "user app" but "user ${REDIS_USERNAME:-app}") as the content is just copied verbatim, and not interpolated.

We could take some inspiration from [dotenv-expand](https://www.npmjs.com/package/dotenv-expand) and expand any variables in content strings; after all, any variable mentioned must be available in the build context already.

Check for:
- [ ] is there any existing library to expand shell variables in *strings*, not .env-style dictionaries?
- [ ] could we defer parsing to a docker command (or another shell command)?
- [ ] are there other places we make transformations that prevent stuff getting properly interpolated?
